#5week (연관규칙마이닝(ARM))
library(arules)
library(arulesViz)
data("Groceries")
Groceries
summary(Groceries)
inspect(Groceries[1:3,])
itemFrequencyPlot(Groceries,col=1:10,topN=15)
itemFrequencyPlot(Groceries,col=1:10,topN=5)
g_rule<-apriori(Groceries,parameter = list(supp=0.02,conf=0.4,minlen=2,maxlen=3))
inspect(g_rule)
plot(g_rule)
plot(g_rule,method='graph')
g_rule2<-apriori(Groceries,parameter = list(supp=0.02,conf=0.4,minlen=2,maxlen=3),appearance = list(default='rhs',lhs='root vegetables'))
inspect(g_rule2)
plot(g_rule2)
plot(g_rule2,method='graph')
g_rule3<-apriori(Groceries,parameter = list(supp=0.02,conf=0.4,minlen=2,maxlen=3),appearance = list(default='rhs',lhs='other vegetables'))
inspect(g_rule3)
plot(g_rule3,method = 'graph')
ipc<-read.transactions("C:/Data/patent_ipc_list.txt",format="basket",sep=",",skip=1)
ipc
inspect(ipc[1:5])
inspect(ipc[1:5,])
summary(ipc)
itemFrequencyPlot(ipc,xlab="IPC CODE",ylab="PROPORTION",col=1:5,topN=10)
ipc_rules<-apriori(ipc,parameter = list(supp=0.05,conf=0.1))
ipc_rules
inspect(ipc_rules)
inspect(head(sort(ipc_rules,by="support"),15))
plot(ipc_rules)
plot(ipc_rules,method='graph')
